// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 添加下载任务
Future<ApiDownloadTask> addDownload({
  required String videoId,
  required String title,
  required String coverUrl,
  required String quality,
  required String url,
}) => RustLib.instance.api.crateApiDownloadAddDownload(
  videoId: videoId,
  title: title,
  coverUrl: coverUrl,
  quality: quality,
  url: url,
);

/// 获取所有下载任务
Future<List<ApiDownloadTask>> getAllDownloads() =>
    RustLib.instance.api.crateApiDownloadGetAllDownloads();

/// 获取指定状态的下载任务
Future<List<ApiDownloadTask>> getDownloadsByStatus({required String status}) =>
    RustLib.instance.api.crateApiDownloadGetDownloadsByStatus(status: status);

/// 暂停下载
Future<bool> pauseDownload({required String taskId}) =>
    RustLib.instance.api.crateApiDownloadPauseDownload(taskId: taskId);

/// 继续下载
Future<bool> resumeDownload({required String taskId}) =>
    RustLib.instance.api.crateApiDownloadResumeDownload(taskId: taskId);

/// 取消/删除下载
Future<bool> deleteDownload({
  required String taskId,
  required bool deleteFile,
}) => RustLib.instance.api.crateApiDownloadDeleteDownload(
  taskId: taskId,
  deleteFile: deleteFile,
);

/// 批量暂停下载
Future<bool> pauseAllDownloads() =>
    RustLib.instance.api.crateApiDownloadPauseAllDownloads();

/// 批量继续下载
Future<bool> resumeAllDownloads() =>
    RustLib.instance.api.crateApiDownloadResumeAllDownloads();

/// 监听下载进度更新
Stream<ApiDownloadTask> subscribeDownloadProgress() =>
    RustLib.instance.api.crateApiDownloadSubscribeDownloadProgress();

/// 获取已下载视频的本地播放路径
Future<String?> getLocalVideoPath({required String videoId}) =>
    RustLib.instance.api.crateApiDownloadGetLocalVideoPath(videoId: videoId);
