// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取所有下载文件夹
Future<List<ApiDownloadFolder>> getDownloadFolders() =>
    RustLib.instance.api.crateApiDownloadFoldersGetDownloadFolders();

/// 创建下载文件夹
Future<ApiDownloadFolder> createDownloadFolder({required String name}) =>
    RustLib.instance.api.crateApiDownloadFoldersCreateDownloadFolder(
      name: name,
    );

/// 重命名下载文件夹
Future<bool> renameDownloadFolder({
  required String folderId,
  required String name,
}) => RustLib.instance.api.crateApiDownloadFoldersRenameDownloadFolder(
  folderId: folderId,
  name: name,
);

/// 删除下载文件夹（视频不会被删除，仅清除视频的文件夹关联）
Future<bool> deleteDownloadFolder({required String folderId}) => RustLib
    .instance
    .api
    .crateApiDownloadFoldersDeleteDownloadFolder(folderId: folderId);

/// 将视频移动到文件夹
Future<bool> moveDownloadsToFolder({
  required List<String> videoIds,
  String? folderId,
}) => RustLib.instance.api.crateApiDownloadFoldersMoveDownloadsToFolder(
  videoIds: videoIds,
  folderId: folderId,
);
