// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `load_saved_cookies`

/// 初始化应用（在 Flutter 启动时调用）
Future<void> initApp({required String dataPath}) =>
    RustLib.instance.api.crateApiInitInitApp(dataPath: dataPath);

/// 设置 Cookies（从 WebView 获取后调用）
Future<void> setCookies({required String cookieString}) =>
    RustLib.instance.api.crateApiInitSetCookies(cookieString: cookieString);

/// 检查是否需要 Cloudflare 验证
Future<bool> checkCloudflare() =>
    RustLib.instance.api.crateApiInitCheckCloudflare();

/// 清除所有 Cookies（登出时调用）
Future<void> clearCookies() => RustLib.instance.api.crateApiInitClearCookies();

/// 获取应用版本
Future<String> getVersion() => RustLib.instance.api.crateApiInitGetVersion();

/// 检查网络连接
Future<bool> checkNetwork() => RustLib.instance.api.crateApiInitCheckNetwork();
