// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取当前用户信息
Future<ApiUserInfo?> getCurrentUser() =>
    RustLib.instance.api.crateApiUserGetCurrentUser();

/// 检查登录状态
Future<bool> isLoggedIn() => RustLib.instance.api.crateApiUserIsLoggedIn();

/// 登出
Future<bool> logout() => RustLib.instance.api.crateApiUserLogout();

/// 获取收藏列表
Future<ApiFavoriteList> getFavorites({required int page}) =>
    RustLib.instance.api.crateApiUserGetFavorites(page: page);

/// 获取稀后观看列表
Future<ApiFavoriteList> getWatchLater({required int page}) =>
    RustLib.instance.api.crateApiUserGetWatchLater(page: page);

/// 获取订阅作者列表
Future<List<ApiAuthorInfo>> getSubscribedAuthors() =>
    RustLib.instance.api.crateApiUserGetSubscribedAuthors();

/// 订阅作者
Future<bool> subscribeAuthor({required String authorId}) =>
    RustLib.instance.api.crateApiUserSubscribeAuthor(authorId: authorId);

/// 取消订阅作者
Future<bool> unsubscribeAuthor({required String authorId}) =>
    RustLib.instance.api.crateApiUserUnsubscribeAuthor(authorId: authorId);

/// 获取播放历史
Future<ApiPlayHistoryList> getPlayHistory({
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiUserGetPlayHistory(
  page: page,
  pageSize: pageSize,
);

/// 添加/更新播放历史
Future<bool> updatePlayHistory({
  required String videoId,
  required String title,
  required String coverUrl,
  required double progress,
  required int duration,
}) => RustLib.instance.api.crateApiUserUpdatePlayHistory(
  videoId: videoId,
  title: title,
  coverUrl: coverUrl,
  progress: progress,
  duration: duration,
);

/// 删除单条播放历史
Future<bool> deletePlayHistory({required String videoId}) =>
    RustLib.instance.api.crateApiUserDeletePlayHistory(videoId: videoId);

/// 清空播放历史
Future<bool> clearPlayHistory() =>
    RustLib.instance.api.crateApiUserClearPlayHistory();

/// 获取视频的播放进度
Future<ApiPlayHistory?> getVideoProgress({required String videoId}) =>
    RustLib.instance.api.crateApiUserGetVideoProgress(videoId: videoId);

/// 设置 Cookie（从 WebView 导入）
Future<bool> setCookies({required List<(String, String)> cookies}) =>
    RustLib.instance.api.crateApiUserSetCookies(cookies: cookies);

/// 设置 Cloudflare Cookie
Future<bool> setCfClearance({required String cookieValue}) =>
    RustLib.instance.api.crateApiUserSetCfClearance(cookieValue: cookieValue);

/// 获取需要 Cloudflare 验证时的 URL 和 User-Agent
Future<ApiCloudflareChallenge?> getCloudflareChallengeInfo() =>
    RustLib.instance.api.crateApiUserGetCloudflareChallengeInfo();
